### ISSUE TITLE
Get to know the code!

### ISSUE THREAD

**Issue by gharveymn** [gharveymn/comp-phys-project#10]
Implement the Dijkstra algorithm (note: not ported to py35 yet) to find the best path through the 2D density field. This should be done in py35. Dictionaries and grids are all set up for use. Check out and run Dijkstra.py in the py27 section to see how the algorithm works. Note that igraph is not compatible for output with py35 since Cairo, the drawing utility it uses, is not compatible.

**Comment by Adnanzai** [comment]
I see you started on this. I too have something to show you. This project has a daughter

On Apr 2, 2017 8:49 PM, Gene Harvey <notifications@github.com> wrote:

Implement the Dijkstra algorithm (note: not ported to py35 yet) to find the best path through the 2D density field. This should be done in py35. Dictionaries and grids are all set up for use. Check out and run Dijkstra.py in the py27 section to see how the algorithm works. Note that igraph is not compatible for output with py35 since Cairo, the drawing utility it uses, is not compatible.
